
tasks:
  - init: npm install
    command: npm run start



# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart