
name: Node.js CI

on:
  push:
    branches: [ "Sebastian-105" ]
  pull_request:
    branches: [ "Sebastian-105" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: npm install
    - run: npm install -g pm2
    - run: npm test
    - run: pm2 restart app-name
