name: Main node.js workflow
run-name: ${{ github.actor }}s Main node.js workflow
on: [push]
jobs:
  running-nodejs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm i
      - name: npm run start
        run: npm start
        env:
          CI: true