name: Main node.js workflow
run-name: ${{ github.actor }}s Main node.js workflow
on: [push]
jobs:
  running-nodejs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install netlify-cli -g
      - run: npm i
      - run: npm start
      - run: npm i pm2@latest
      # - run: npm run start
        env:
          CI: false