name: Sebastian-105

on:
  pull_request:
    branches: [Sebastian-105]

  push:
    branches: [Sebastian-105]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          npm install
          npm run test

      - name: Deploy
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/Sebastian-105'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          nDeply_url: ${{ secrets.Netlify_Deploy_hook }}
        run: |
          curl "$deploy_url"
          curl -X POST -d {} $nDeply_url



    